[package]
name = "weggli-native"
version = "0.1.0"
edition = "2021"

[lib]
name = "weggli_native"
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2"
weggli = { git = "https://github.com/googleprojectzero/weggli.git", rev = "07cbd6223b07d96ada3a22d3ef850a628412c508" }
