name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: cargo fmt && git diff --exit-code

      - name: Lint
        run: |
          rustup update
          rustup component add clippy
          cargo clippy -- \
            -D warnings -D clippy::expect_used -D clippy::unwrap_used -D clippy::panic

  demo:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Update rust
      run: rustup update

    - name: Build
      run: cargo build

    - name: Demo
      run: |
        cd demo
        make
        ./demo

  cmake:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Update rust
      run: rustup update

    - name: Configure
      run: |
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -S . \
          -B build
    - name: Build
      run: cmake --build build --verbose
    - name: Install
      run: cmake --install build --prefix install
