name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  demo:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Update rust
      run: rustup update

    - name: Install cbindgen
      run: cargo install --force cbindgen

    - name: Build
      run: cargo build

    - name: Demo
      run: |
        cd demo
        make
        ./demo

  cmake:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Update rust
      run: rustup update

    - name: Install cbindgen
      run: cargo install --force cbindgen

    - name: Configure
      run: |
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -S . \
          -B build
    - name: Build
      run: cmake --build build --verbose
    - name: Install
      run: cmake --install build --prefix install
